In [1]:
pip install transformers

In [2]:
!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.1/507.1 kB 4.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 6.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 7.5 MB/s eta 0:00:00


In [3]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel
from datasets import Dataset, Value, Features, Sequence
from sklearn.model_selection import train_test_split

In [4]:
with open("ferdousi.txt", "r", encoding="utf-8") as file:
    lines = file.readlines()

In [5]:
poems = [line.strip() for line in lines[2:] if line.strip()]
grouped_poems_x = [f"{poems[i]}\n{poems[i + 1]}" for i in range(0, len(poems) - 1, 4)]
grouped_poems_y = [f"{poems[i]}\n{poems[i + 1]}" for i in range(2, len(poems) - 1, 4)]
print(grouped_poems_x[0])
print(grouped_poems_y[0])
grouped_poems = [f"{poems[i]}\n{poems[i + 1]}" for i in range(0, len(poems) - 1, 2)]

به نام خداوند جان و خرد
کزین برتر اندیشه برنگذرد
خداوند نام و خداوند جای
خداوند روزی ده رهنمای


In [6]:
x_train, x_test, y_train, y_test = train_test_split(grouped_poems_x, grouped_poems_y, test_size=0.2, random_state=42)

In [7]:
train_data = Dataset.from_dict({"input": x_train, "output": y_train})
test_data = Dataset.from_dict({"input": x_test, "output": y_test})

In [8]:
import pandas as pd
import numpy as np

from pathlib import Path

import torch
from transformers import AutoTokenizer, AutoConfig, AutoModelWithLMHead
from transformers import AutoTokenizer, GPT2LMHeadModel, GPT2Config

from IPython import display

In [9]:
model_name_or_path = "HooshvareLab/gpt2-fa"

tokenizer = AutoTokenizer.from_pretrained(
    model_name_or_path,
    bos_token='<s>',
    eos_token='</s>',
    pad_token='<pad>',
    unk_token='<unk>'
)
tokenizer.add_special_tokens({
    "bos_token": '</s>',
    "eos_token": '</s>',
    "pad_token": '<pad>',
    "unk_token": '<unk>'
})

config = AutoConfig.from_pretrained(
    model_name_or_path,
    bos_token_id=tokenizer("<s>")["input_ids"][0],
    eos_token_id=tokenizer("</s>")["input_ids"][0],
    pad_token_id=tokenizer("<pad>")["input_ids"][0],
    unk_token_id=tokenizer("<unk>")["input_ids"][0],
)

tokenizer.save_pretrained("/content/gpt2/")
config.save_pretrained("/content/gpt2/")

!wget "https://huggingface.co/HooshvareLab/gpt2-fa/resolve/main/pytorch_model.bin" -P /content/gpt2/
!wget "https://huggingface.co/HooshvareLab/gpt2-fa/resolve/main/tokenizer.json" -P /content/gpt2/

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/728 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/808 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/875k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.75M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/14.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/104 [00:00<?, ?B/s]

--2024-01-21 15:51:17--  https://huggingface.co/HooshvareLab/gpt2-fa/resolve/main/pytorch_model.bin
Resolving huggingface.co (huggingface.co)... 18.164.174.23, 18.164.174.17, 18.164.174.118, ...
Connecting to huggingface.co (huggingface.co)|18.164.174.23|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn-lfs.huggingface.co/HooshvareLab/gpt2-fa/46b0b806c740a0f0a9f056f5574c5fa896166fe844945fd3c849bf34365e5060?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27pytorch_model.bin%3B+filename%3D%22pytorch_model.bin%22%3B&response-content-type=application%2Foctet-stream&Expires=1706111477&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwNjExMTQ3N319LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9Ib29zaHZhcmVMYWIvZ3B0Mi1mYS80NmIwYjgwNmM3NDBhMGYwYTlmMDU2ZjU1NzRjNWZhODk2MTY2ZmU4NDQ5NDVmZDNjODQ5YmYzNDM2NWU1MDYwP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiZyZXNwb25zZS1jb250ZW50LXR5cGU9KiJ9XX0_&

In [10]:
l = 0
for i in range(len(grouped_poems)):
  l_new = len(tokenizer.encode(grouped_poems[i]))
  if l_new > l:
    l = l_new
print(l)

23


In [11]:
tokenizer = AutoTokenizer.from_pretrained(
    "/content/gpt2",
    bos_token='<s>',
    eos_token='</s>',
    pad_token='<pad>'
)

print(tokenizer.encode(grouped_poems_x[0]))
print(tokenizer.encode("<s>"))
print(tokenizer.encode("</s>"))
print(tokenizer.encode("<pad>"))
print(tokenizer.encode("<|startoftext|>"))
print(tokenizer.encode("<sep>"))

[490, 561, 6733, 1305, 293, 2964, 209, 2639, 297, 3206, 6188, 29631, 383, 343]
[0]
[2]
[1]
[6]
[9]


In [18]:
from torch.utils.data import Dataset
import torch
torch.manual_seed(42)


class MTGDataset(Dataset):

    def __init__(self, txt_list, tokenizer, max_length=1024):

        self.tokenizer = tokenizer
        self.input_ids = []
        self.attn_masks = []

        for txt in txt_list:
            encodings_dict = tokenizer('<s>' + txt + '</s>',
                                       truncation=True,
                                       max_length=max_length,
                                       padding="max_length")

            self.input_ids.append(torch.tensor(encodings_dict['input_ids']))
            self.attn_masks.append(torch.tensor(encodings_dict['attention_mask']))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.attn_masks[idx]

In [19]:
max_seq = 23
from torch.utils.data import random_split

dataset = MTGDataset(grouped_poems, tokenizer, max_length=max_seq)

# Split into training and validation sets
train_size = int(0.9 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

f'There are {len(train_dataset)} samples for training, and {len(val_dataset)} samples for validation testing'

'There are 44647 samples for training, and 4961 samples for validation testing'

In [20]:
print(train_dataset[0][0])

tensor([    0, 10048,   274,   747, 10034,   326,  9908,   209,   800,   312,
        15520,   293,  6484,  1102, 22640,   907,     2,     1,     1,     1,
            1,     1,     1])


In [21]:
train_dataset[0]

(tensor([    0, 10048,   274,   747, 10034,   326,  9908,   209,   800,   312,
         15520,   293,  6484,  1102, 22640,   907,     2,     1,     1,     1,
             1,     1,     1]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]))

In [22]:
from torch.utils.data import DataLoader, RandomSampler, SequentialSampler

train_dataloader = DataLoader(
    train_dataset,
    sampler=RandomSampler(train_dataset),
    batch_size=8
)

validation_dataloader = DataLoader(
    val_dataset,
    sampler=SequentialSampler(val_dataset),
    batch_size=8
)

In [23]:
import random
from transformers import GPT2LMHeadModel, GPT2Config
import numpy as np

configuration = GPT2Config.from_pretrained('./gpt2', output_hidden_states=False)

model = GPT2LMHeadModel.from_pretrained("./gpt2", config=configuration)
model.resize_token_embeddings(len(tokenizer))

device = torch.device("cuda")
model.cuda()

seed_val = 42

random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)

In [24]:
epochs = 3
warmup_steps = 1e2
sample_every = 300

In [25]:
from transformers import AdamW
optimizer = AdamW(
    model.parameters(),
    lr=5e-4,
    eps=1e-8
)

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [26]:
from transformers import get_linear_schedule_with_warmup

total_steps = len(train_dataloader) * epochs

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=warmup_steps,
    num_training_steps=total_steps)

In [27]:
sample_input = grouped_poems[0]
print(sample_input)
sample_input_ids = torch.tensor(tokenizer([sample_input])["input_ids"])
sample_input_ids = sample_input_ids.to(device)


به نام خداوند جان و خرد
کزین برتر اندیشه برنگذرد


In [28]:
sample_input_ids

tensor([[  490,   561,  6733,  1305,   293,  2964,   209,  2639,   297,  3206,
          6188, 29631,   383,   343]], device='cuda:0')

In [29]:
len(sample_input_ids[0])

14

In [31]:
sample_outputs = model.generate(
    input_ids=sample_input_ids,
    do_sample=True,
    top_k=50,
    max_length=50,
    top_p=0.95,
    num_return_sequences=1
)
print(sample_outputs[0][14:])

for i, sample_output in enumerate(sample_outputs[0][14:].unsqueeze(0)):
    gen_sample_output = tokenizer.decode(sample_output, skip_special_tokens=False)
    gen_sample_output = gen_sample_output.replace("<|startoftext|>", "\n")
    gen_sample_output = gen_sample_output.replace("<s>", "")
    gen_sample_output = gen_sample_output.replace("</s>", "")
    gen_sample_output = gen_sample_output.replace("<sep>", "\n")

    print(f'Example output: {gen_sample_output}')

tensor([  293,  1088,   293,  1494,   298,   747,  6188,   285,   350,   293,
          927,   285,   350,   293,  6188,   285,   350,   293,  4954,   451,
         6818,   293, 27808,   293,  1554,   293,  3632,   293,   850,   377,
          460,    24,   326,  1624,   303,   358], device='cuda:0')
Example output:  و جهان و انسان در همه اندیشه‌ها و زندگی‌ها و اندیشه‌ها و افکار او شریک و همدم و دوست و متحد و همراه خود داشت. این نگاه به آن


In [34]:
import random
import time
import datetime
from tqdm import tqdm


def format_time(elapsed):
    return str(datetime.timedelta(seconds=int(round((elapsed)))))


total_t0 = time.time()

training_stats = []

model = model.to(device)

for epoch_i in tqdm(range(0, epochs), position=0):

    print(f'Beginning epoch {epoch_i + 1} of {epochs}')

    t0 = time.time()

    total_train_loss = 0

    model.train()

    for step, batch in tqdm(enumerate(train_dataloader), total=len(train_dataloader), position=0):

        b_input_ids = batch[0].to(device)
        #print(b_input_ids)
        b_labels = batch[0].to(device)
        #print(b_labels)
        b_masks = batch[1].to(device)
        #print(b_masks)
        model.zero_grad()

        outputs = model(b_input_ids, labels=b_labels, attention_mask=b_masks, token_type_ids=None)

        loss = outputs[0]

        batch_loss = loss.item()
        #print(batch_loss)
        total_train_loss += batch_loss

        if step % sample_every == 0 and not step == 0:

            elapsed = format_time(time.time() - t0)
            print()
            print(f'Batch {step} of {len(train_dataloader)}. Loss:{batch_loss}. Time:{elapsed}')

            model.eval()
            random_number = random.randint(1, 44647)
            sample_input = grouped_poems[random_number]
            sample_input_ids = torch.tensor(tokenizer([sample_input])["input_ids"])
            sample_input_ids = sample_input_ids.to(device)

            sample_outputs = model.generate(
                input_ids=sample_input_ids,
                do_sample=True,
                top_k=50,
                max_length=50,
                top_p=0.95,
                num_return_sequences=1
            )
            for i, sample_output in enumerate(sample_outputs):
                gen_sample_output = tokenizer.decode(sample_output, skip_special_tokens=False)
                gen_sample_output = gen_sample_output.replace("<|startoftext|>", "\n")
                gen_sample_output = gen_sample_output.replace("<s>", "")
                gen_sample_output = gen_sample_output.replace("</s>", "")
                gen_sample_output = gen_sample_output.replace("<sep>", "\n")

                print(f'Example output: {gen_sample_output}')

            model.train()

        loss.backward()
        optimizer.step()
        scheduler.step()

    avg_train_loss = total_train_loss / len(train_dataloader)

    training_time = format_time(time.time() - t0)

    print()
    print(f'Average Training Loss: {avg_train_loss}. Epoch time: {training_time}')
    print()

    t0 = time.time()

    model.eval()

    total_eval_loss = 0
    nb_eval_steps = 0
    for batch in tqdm(validation_dataloader, total=len(validation_dataloader), position=0):

        b_input_ids = batch[0].to(device)
        b_labels = batch[0].to(device)
        b_masks = batch[1].to(device)

        with torch.no_grad():

            outputs = model(b_input_ids, attention_mask=b_masks, labels=b_labels)

            loss = outputs[0]

        batch_loss = loss.item()
        total_eval_loss += batch_loss

    avg_val_loss = total_eval_loss / len(validation_dataloader)

    validation_time = format_time(time.time() - t0)

    print()
    print(f'Validation loss: {avg_val_loss}. Validation Time: {validation_time}')
    print()
    training_stats.append(
        {
            'epoch': epoch_i + 1,
            'Training Loss': avg_train_loss,
            'Valid. Loss': avg_val_loss,
            'Training Time': training_time,
            'Validation Time': validation_time
        }
    )

print(f'Total training took {format_time(time.time()-total_t0)}')

  0%|          | 0/3 [00:00<?, ?it/s]

Beginning epoch 1 of 3


  5%|▌         | 301/5581 [00:28<07:48, 11.27it/s]


Batch 300 of 5581. Loss:2.751617670059204. Time:0:00:28
Example output: ز فرزند پرسید دانا سخن
وزو بایدم پاسخ افگند بن


 11%|█         | 601/5581 [00:54<07:22, 11.25it/s]


Batch 600 of 5581. Loss:2.376467227935791. Time:0:00:54
Example output: شگفتی ز دیدار او خیره ماند
بروبر همی نام یزدان بخواند


 16%|█▌        | 901/5581 [01:20<06:51, 11.38it/s]


Batch 900 of 5581. Loss:2.6373300552368164. Time:0:01:20
Example output: بیامد هم آنگاه سالار بار
فرستاده را برد زی شهریار


 22%|██▏       | 1201/5581 [01:46<06:38, 10.99it/s]


Batch 1200 of 5581. Loss:3.0207910537719727. Time:0:01:46
Example output: بدان ای پر اندیشه سالار من
بهر کار شایستهٔ کار من


 27%|██▋       | 1501/5581 [02:12<06:11, 10.98it/s]


Batch 1500 of 5581. Loss:2.382697820663452. Time:0:02:12
Example output: ایا باد بگذر بایران زمین
پیامی بر از من بشاه گزین


 32%|███▏      | 1801/5581 [02:38<05:46, 10.90it/s]


Batch 1800 of 5581. Loss:2.9276742935180664. Time:0:02:38
Example output: بجان شنگل از دست رستم بجست
زره بود و جوشن تنش را نخست


 38%|███▊      | 2101/5581 [03:04<05:19, 10.90it/s]


Batch 2100 of 5581. Loss:2.6807782649993896. Time:0:03:04
Example output: چو افراسیاب این سخن باز جست
همه گفت گرسیوز آمد درست


 43%|████▎     | 2401/5581 [03:31<05:35,  9.48it/s]


Batch 2400 of 5581. Loss:2.3838460445404053. Time:0:03:31
Example output: چنین گفت کاو را گرازست نام
که در چنگ شیران ندارد لگام


 48%|████▊     | 2701/5581 [03:57<04:15, 11.26it/s]


Batch 2700 of 5581. Loss:2.4562876224517822. Time:0:03:58
Example output: کجا گفته بودند بهرام را
که ما روز جنگ از پی نام را


 54%|█████▍    | 3001/5581 [04:23<03:47, 11.34it/s]


Batch 3000 of 5581. Loss:2.5451319217681885. Time:0:04:24
Example output: زمانه شد از گرد چون پر چرغ
جهانجوی بگذشت بر مای و مرغ


 59%|█████▉    | 3301/5581 [04:49<03:21, 11.34it/s]


Batch 3300 of 5581. Loss:2.4419755935668945. Time:0:04:50
Example output: که ما را ز بدها تو باشی پناه
چو گم شد سر تاج کاووس شاه


 65%|██████▍   | 3601/5581 [05:15<02:54, 11.36it/s]


Batch 3600 of 5581. Loss:2.409825086593628. Time:0:05:16
Example output: جهاندار دانا و پروردگار
چنین آفرید اختر روزگار


 70%|██████▉   | 3902/5581 [05:42<02:27, 11.39it/s]


Batch 3900 of 5581. Loss:2.412935256958008. Time:0:05:42
Example output: بگفتند و هر دو برابر شدند
به اندیشه از ماه برتر شدند


 75%|███████▌  | 4202/5581 [06:07<02:00, 11.46it/s]


Batch 4200 of 5581. Loss:2.5904500484466553. Time:0:06:08
Example output: ز پروازش آورد نزد پدر
رسیده به زیر برش موی سر


 81%|████████  | 4501/5581 [06:36<01:48,  9.96it/s]


Batch 4500 of 5581. Loss:2.4804294109344482. Time:0:06:36
Example output: بدان را ز بد دست کوته کنم
زمین را بکین رنگ دیبه کنم


 86%|████████▌ | 4801/5581 [07:03<01:08, 11.41it/s]


Batch 4800 of 5581. Loss:2.564056158065796. Time:0:07:03
Example output: برین کار یزدان ترا راز نیست
اگر جانت با دیو انباز نیست


 91%|█████████▏| 5101/5581 [07:29<00:42, 11.38it/s]


Batch 5100 of 5581. Loss:2.5814435482025146. Time:0:07:29
Example output: دگر چون گنه کار جوید همی
دل از بیگناهان بشوید همی


 97%|█████████▋| 5401/5581 [07:55<00:15, 11.28it/s]


Batch 5400 of 5581. Loss:2.573159694671631. Time:0:07:55
Example output: سپهکش چو رستم سپهدار طوس
بابر اندر اورده آوای کوس


100%|██████████| 5581/5581 [08:12<00:00, 11.34it/s]



Average Training Loss: 2.531483612913232. Epoch time: 0:08:12



 33%|███▎      | 1/3 [08:28<16:57, 508.62s/it]


Validation loss: 2.4457291439535536. Validation Time: 0:00:16

Beginning epoch 2 of 3


  5%|▌         | 302/5581 [00:26<07:43, 11.39it/s]


Batch 300 of 5581. Loss:1.818761944770813. Time:0:00:26
Example output: سپاهش پراگنده از هر سوی
به تاراج کردن به هر پهلوی


 11%|█         | 602/5581 [00:52<07:16, 11.40it/s]


Batch 600 of 5581. Loss:2.010439395904541. Time:0:00:52
Example output: همی بود یک چند باگفت وگوی
جهانجوی با لشکری جنگجوی


 16%|█▌        | 902/5581 [01:18<06:48, 11.44it/s]


Batch 900 of 5581. Loss:2.2734479904174805. Time:0:01:18
Example output: که بر هم زند چشم زیر و زبر
بریده به لشکر نمایمش سر


 22%|██▏       | 1202/5581 [01:44<06:25, 11.35it/s]


Batch 1200 of 5581. Loss:2.2192277908325195. Time:0:01:44
Example output: پرستیدن ایزد آمدش رای
بینداخت تاج و بپردخت جای


 27%|██▋       | 1502/5581 [02:10<05:58, 11.39it/s]


Batch 1500 of 5581. Loss:2.2257883548736572. Time:0:02:10
Example output: بدانگه که دریای یاقوت زرد
زند موج بر کشور لاژورد


 32%|███▏      | 1802/5581 [02:36<05:32, 11.37it/s]


Batch 1800 of 5581. Loss:1.873155951499939. Time:0:02:36
Example output: سواری بیامد خرید آن جوال
ندادش بها و بپیچید یال


 38%|███▊      | 2102/5581 [03:02<05:04, 11.42it/s]


Batch 2100 of 5581. Loss:2.0892744064331055. Time:0:03:02
Example output: ز گرگان بیامد به شهر نسا
یکی رهنمون پیش پر کیمیا


 43%|████▎     | 2402/5581 [03:29<04:39, 11.39it/s]


Batch 2400 of 5581. Loss:1.9041907787322998. Time:0:03:29
Example output: هم اندرز بهمن به رستم بگفت
برآورد رازی که بود از نهفت


 48%|████▊     | 2702/5581 [03:55<04:12, 11.40it/s]


Batch 2700 of 5581. Loss:1.8880038261413574. Time:0:03:55
Example output: ازین پس مرا جای پیکار نیست
به از راستی در جهان کار نیست


 54%|█████▍    | 3002/5581 [04:21<03:48, 11.29it/s]


Batch 3000 of 5581. Loss:2.2204229831695557. Time:0:04:21
Example output: سکندر بدو گفت نشنیده ام
نه کس را ز شاهان چنین دیده ام


 59%|█████▉    | 3302/5581 [04:46<03:19, 11.40it/s]


Batch 3300 of 5581. Loss:2.0804967880249023. Time:0:04:47
Example output: چنان بد که بنشست روزی بخوان
بفرمود کاین موبدان را بخوان


 65%|██████▍   | 3602/5581 [05:12<02:53, 11.39it/s]


Batch 3600 of 5581. Loss:2.3723225593566895. Time:0:05:13
Example output: ولیکن بدین گفته پاسخ شنو
خرد یاد کن بخت را پیشرو


 70%|██████▉   | 3902/5581 [05:38<02:28, 11.32it/s]


Batch 3900 of 5581. Loss:2.1684868335723877. Time:0:05:39
Example output: چنین سال پنجه برنجید نیز
ندید از هنر بر خرد بسته چیز


 75%|███████▌  | 4202/5581 [06:04<02:01, 11.37it/s]


Batch 4200 of 5581. Loss:1.5218098163604736. Time:0:06:05
Example output: گذشته ز رستم به ایران سوار
ندانم که با من کند کارزار


 81%|████████  | 4502/5581 [06:30<01:39, 10.80it/s]


Batch 4500 of 5581. Loss:1.7536064386367798. Time:0:06:31
Example output: من او را بدین گفته بیجان کنم
برو بر دل دوده پیچان کنم


 86%|████████▌ | 4802/5581 [06:56<01:10, 11.07it/s]


Batch 4800 of 5581. Loss:1.8647781610488892. Time:0:06:57
Example output: کنون گاو آن زیر چرم اندر است
که پاداش و بادافره دیگرست


 91%|█████████▏| 5102/5581 [07:22<00:43, 10.97it/s]


Batch 5100 of 5581. Loss:1.9645648002624512. Time:0:07:23
Example output: سراپردهٔ نو بپرداختند
نشستنگه خسروی ساختند


 97%|█████████▋| 5402/5581 [07:48<00:16, 10.95it/s]


Batch 5400 of 5581. Loss:1.93436861038208. Time:0:07:49
Example output: ز توران سوی زابلستان کشید
به نزدیک فرخنده دستان کشید


100%|██████████| 5581/5581 [08:04<00:00, 11.52it/s]



Average Training Loss: 2.042650837215594. Epoch time: 0:08:04



 67%|██████▋   | 2/3 [16:44<08:21, 501.24s/it]


Validation loss: 2.347630885488169. Validation Time: 0:00:12

Beginning epoch 3 of 3


  5%|▌         | 302/5581 [00:26<07:44, 11.36it/s]


Batch 300 of 5581. Loss:1.5422347784042358. Time:0:00:26
Example output: شما دل مدارید ازو مستمند
کجا کشته شد زیر خم کمند


 11%|█         | 602/5581 [00:52<07:18, 11.37it/s]


Batch 600 of 5581. Loss:1.667983889579773. Time:0:00:52
Example output: فگندیم هرگونه رایی ز بن
ز دستان گشاید همی این سخن


 16%|█▌        | 902/5581 [01:18<06:51, 11.38it/s]


Batch 900 of 5581. Loss:1.6368732452392578. Time:0:01:18
Example output: غمی گشت سهراب را دل ازان
که جایی ز رستم نیامد نشان


 22%|██▏       | 1202/5581 [01:43<06:24, 11.38it/s]


Batch 1200 of 5581. Loss:1.3480781316757202. Time:0:01:44
Example output: به الکوس رفت آگهی زین سخن
که سالار توران چه افگند بن


 27%|██▋       | 1502/5581 [02:09<05:57, 11.40it/s]


Batch 1500 of 5581. Loss:1.1791120767593384. Time:0:02:10
Example output: پرستش بهی برکنم زین جهان
سپارم ترا تاج و تخت مهان


 32%|███▏      | 1802/5581 [02:35<05:34, 11.31it/s]


Batch 1800 of 5581. Loss:1.6628597974777222. Time:0:02:36
Example output: کمان را به زه کرد و بگشاد بر
نبد مرغ را پیش تیرش گذر


 38%|███▊      | 2102/5581 [03:01<05:05, 11.39it/s]


Batch 2100 of 5581. Loss:1.6209479570388794. Time:0:03:02
Example output: بدو گفت گشتاسپ کای شهریار
ابی تو مبیناد کس روزگار


 43%|████▎     | 2402/5581 [03:27<04:39, 11.36it/s]


Batch 2400 of 5581. Loss:1.5164458751678467. Time:0:03:28
Example output: بدان مرزبانان چنین گفت شاه
که امشب نرانیم زین جایگاه


 48%|████▊     | 2702/5581 [03:53<04:13, 11.36it/s]


Batch 2700 of 5581. Loss:1.548453450202942. Time:0:03:54
Example output: رسیدند پس پیش خاقان چین
سراسر زبانها پر از آفرین


 54%|█████▍    | 3002/5581 [04:19<03:46, 11.39it/s]


Batch 3000 of 5581. Loss:1.3970307111740112. Time:0:04:20
Example output: ببستند ز آهن بگردش سرای
پس پشت پیلان جنگی بپای


 59%|█████▉    | 3302/5581 [04:45<03:20, 11.39it/s]


Batch 3300 of 5581. Loss:1.5139240026474. Time:0:04:46
Example output: سپاهی که سگسار خوانندشان
پلنگان جنگی نمایندشان


 65%|██████▍   | 3602/5581 [05:11<02:53, 11.40it/s]


Batch 3600 of 5581. Loss:1.515148639678955. Time:0:05:12
Example output: خور و خواب و آرام بر دشت و کوه
برهنه به هر جای گشته گروه


 70%|██████▉   | 3902/5581 [05:37<02:26, 11.47it/s]


Batch 3900 of 5581. Loss:1.464749813079834. Time:0:05:37
Example output: به بالای تو بر زمین شاه نیست
به دیدار تو بر فلک ماه نیست


 75%|███████▌  | 4202/5581 [06:03<02:01, 11.37it/s]


Batch 4200 of 5581. Loss:1.4223430156707764. Time:0:06:03
Example output: ازان مردری تاج شاهنشهی
ترا شد سر از جنگ جستن تهی


 81%|████████  | 4502/5581 [06:29<01:34, 11.36it/s]


Batch 4500 of 5581. Loss:1.7548373937606812. Time:0:06:29
Example output: بفرمای کاهنگران آورند
چو سوهان و پتک گران آورند


 86%|████████▌ | 4802/5581 [06:55<01:08, 11.40it/s]


Batch 4800 of 5581. Loss:1.72234046459198. Time:0:06:55
Example output: رهش باز دادند و بگریختند
به آورد با او نیاویختند


 91%|█████████▏| 5102/5581 [07:21<00:42, 11.40it/s]


Batch 5100 of 5581. Loss:1.4720463752746582. Time:0:07:21
Example output: ز هنگام کاوس تا کیقباد
ازین بوم و برکس نکردست یاد


 97%|█████████▋| 5402/5581 [07:47<00:16, 11.17it/s]


Batch 5400 of 5581. Loss:1.6890448331832886. Time:0:07:47
Example output: دو تن نامداران توران سپاه
برفتند زین سان دلاور براه


100%|██████████| 5581/5581 [08:03<00:00, 11.55it/s]



Average Training Loss: 1.5467901395824386. Epoch time: 0:08:03



100%|██████████| 3/3 [24:59<00:00, 499.80s/it]


Validation loss: 2.4818314283174403. Validation Time: 0:00:12

Total training took 0:24:59
